FROM postgres:18-trixie

ENV POSTGIS_MAJOR=3
ENV POSTGIS_VERSION=3.6.1+dfsg-1.pgdg13+1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
    postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts \
    && rm -rf /var/lib/apt/lists/*

COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/
COPY ./update-postgis.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/initdb-postgis.sh